version: "3.8"

services:
  database:
    image: postgres:14-alpine
    container_name: kupi_db
    env_file:
      - ./envs/db.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PGDATA
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - kupi_net
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kupi_backend
    env_file:
      - ./envs/backend.env
    depends_on:
      - database
    ports:
      - "4000:4000"
    command: ["node", "dist/main.js"]
    networks:
      - kupi_net
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kupi_frontend
    env_file:
      - ./envs/frontend.env
    ports:
      - "8081:80"
    command: ["node", "dist/main.js"]
    networks:
      - kupi_net
    restart: always

volumes:
  db_data:
    driver: local

networks:
  kupi_net:
    driver: bridge